//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.eAita
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CCTC_THANHPHAN> CCTC_THANHPHAN { get; set; }
        public DbSet<DM_CHUCNANG> DM_CHUCNANG { get; set; }
        public DbSet<DM_NGUOIDUNG> DM_NGUOIDUNG { get; set; }
        public DbSet<DM_THAOTAC> DM_THAOTAC { get; set; }
        public DbSet<DM_VAITRO> DM_VAITRO { get; set; }
        public DbSet<HUYEN> HUYEN { get; set; }
        public DbSet<NGUOIDUNG_VAITRO> NGUOIDUNG_VAITRO { get; set; }
        public DbSet<TAILIEUDINHKEM> TAILIEUDINHKEM { get; set; }
        public DbSet<TINH> TINH { get; set; }
        public DbSet<VAITRO_CHUCNANG> VAITRO_CHUCNANG { get; set; }
        public DbSet<VAITRO_THAOTAC> VAITRO_THAOTAC { get; set; }
        public DbSet<XA> XA { get; set; }
        public DbSet<DM_LOAI_DONVI> DM_LOAI_DONVI { get; set; }
    }
}
